/**
 * usePersonalData Partial Hook
 * Manages core profile identity: name, email, username, and bio.
 */
import { useState } from 'react';
import { FullProfile } from '../../interfaces/types/FullProfile';
import type { User } from '@pulwave/entity-auth';
import { contactService } from '../../services/contactService';

export interface PersonalFormData {
    username: string;
    first_name: string;
    middle_name: string;
    last_name: string;
    display_name: string;
    email: string;
    phone_code: string;
    phone_number: string;
    phone_secondary_code: string;
    phone_secondary_number: string;
    date_of_birth: string;
    gender: string;
    pronouns: string;
    bio: string;
    website: string;
    linkedin_url: string;
    twitter_url: string;
    facebook_url: string;
}

export const usePersonalData = () => {
    const [formData, setFormData] = useState<PersonalFormData>({
        username: '',
        first_name: '',
        middle_name: '',
        last_name: '',
        display_name: '',
        email: '',
        phone_code: '',
        phone_number: '',
        phone_secondary_code: '',
        phone_secondary_number: '',
        date_of_birth: '',
        gender: '',
        pronouns: '',
        bio: '',
        website: '',
        linkedin_url: '',
        twitter_url: '',
        facebook_url: '',
    });
    const [displayNameManuallyEdited, setDisplayNameManuallyEdited] = useState(false);

    const mapProfileToPersonalData = (profile: FullProfile | null, user: User | null) => {
        if (!profile) return;

        const autoGeneratedName = `${profile.first_name || ''} ${profile.last_name || ''}`.trim();
        const isCustom = profile.display_name && profile.display_name !== autoGeneratedName;
        setDisplayNameManuallyEdited(!!isCustom);

        // Map contacts
        const contacts = profile.contacts || [];
        const contactFormData = contactService.mapToFormData(contacts);

        setFormData({
            username: profile.username || '',
            first_name: profile.first_name || '',
            middle_name: profile.middle_name || '',
            last_name: profile.last_name || '',
            display_name: profile.display_name || '',
            email: user?.email || profile.email || '',
            phone_code: contactFormData.phone_code,
            phone_number: contactFormData.phone_number,
            phone_secondary_code: contactFormData.phone_secondary_code,
            phone_secondary_number: contactFormData.phone_secondary_number,
            date_of_birth: profile.date_of_birth || '',
            gender: profile.gender || '',
            pronouns: profile.pronouns || '',
            bio: profile.bio || '',
            website: profile.social_profiles?.find(s => s.platform === 'website')?.url || '',
            linkedin_url: profile.social_profiles?.find(s => s.platform === 'linkedin')?.url || '',
            twitter_url: profile.social_profiles?.find(s => s.platform === 'twitter')?.url || '',
            facebook_url: profile.social_profiles?.find(s => s.platform === 'facebook')?.url || '',
        });
    };

    const handlePersonalChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
        const { name, value } = e.target;

        if (name === 'display_name') {
            setDisplayNameManuallyEdited(true);
        }

        setFormData(prev => {
            const newData = { ...prev, [name]: value };

            if ((name === 'first_name' || name === 'last_name') && !displayNameManuallyEdited) {
                const firstName = name === 'first_name' ? value : prev.first_name;
                const lastName = name === 'last_name' ? value : prev.last_name;
                newData.display_name = `${firstName || ''} ${lastName || ''}`.trim();
            }

            return newData;
        });
    };

    return {
        formData,
        setFormData,
        displayNameManuallyEdited,
        setDisplayNameManuallyEdited,
        mapProfileToPersonalData,
        handlePersonalChange,
    };
};
